qmspec:

  #
  # accept license - required
  #
  license:
    accept: 'true'

  #
  # create image pull secret
  # oc create secret docker-registry image-pull-secret --docker-username=<u> --docker-password=<p> --docker-email=<e>
  #
  imagePullSecrets: 
    - name: 'image-pull-secret'

  #
  # create tls secret
  # oc create secret generic qm-tls --from-file=tls.key=</path/to/tls.key> --from-file=tls.crt=</path/to/tls.crt> --from-file=ca.crt=</path/to/ca.crt>
  #
  pki:
    tlsSecretName: '' # 'qm-tls'

  #
  # create ldap secret
  # oc create secret generic ldapcreds --from-literal=password=<ldappassword>
  #
  ldapCredsSecret:
    name: 'ldapcreds' # ldapcreds

  # queue manager name - required
  name: qm20

  # custom docker image - required
  image: docker.io/simong5000/txmq-mq-base-rpm-9.2.2.0:110

  # image pull policy IfNotPresent|Always
  imagePoolPolicy: Always

  #
  # set environment variables
  #
  env:
    # start mq web console
  - name: MQ_START_MQWEB
    value: "1"

#  resources:
#    limits:
#      cpu: "250m"
#      memory: "512Mi"
#    requests:
#      cpu: "250m"
#      memory: "512Mi"

  storage:
    usePvc: 'true'
    pvcName: qm-sts-claim
    storageClass: standard
    accessMode: ReadWriteOnce
    # @todo
    deleteClaim: false
    size: 2Gi

#
# mq web console configuration
#
webuser:
  #
  # groups mapped to built-in web roles
  #
  webroles:
  - name: MQWebAdmin
    groups: [devs]
  - name: MQWebAdminRO
    groups: [devs]
  - name: MQWebUser
    groups: [devs]

  #
  # groups mapped to built-in api roles
  #
  apiroles:
  - name: MQWebAdmin
    groups: [devs]
  - name: MQWebAdminRO
    groups: [devs]
  - name: MQWebUser
    groups: ["devs"]

  #
  # ldap registry
  #
  ldapregistry:
    connect:
      realm: openldap
      host: openldap.default.svc.cluster.local
      port: 389
      ldaptype: Custom
      binddn: cn=admin,dc=szesto,dc=com
      #
      # bind password is defined in ldap secret
      # or in the vault if configured
      # otherwise define bind password here.
      #
      bindpassword: ""
      basedn: dc=szesto,dc=com
      sslenabled: false

    # group metadata
    groupdef:
      objectclass: groupOfNames
      groupnameattr: cn
      groupmembershipattr: member

    # user metadata
    userdef:
      objectclass: inetOrgPerson
      usernameattr: uid
