qmspec:

  version: 9.2.2.0
  license: {}
  licenseAnnotations: {}

  annotations: {}

  imagePullSecrets:
    - name: image-pull-secret

  pki:
    tlsSecretName: qm-tls
    enableTls: 1

  qmconf:
    name: qm20
    image: docker.io/simong5000/txmq-mq-adv-rpm:104
    imagePoolPolicy: Always

    env:
    - name: MQ_START_MQWEB
      value: "1"

    resources: {}

    storage:
      pvcName: qm-sts-claim
#      storageClass: managed-nfs-storage
      storageClass: standard
      accessMode: ReadWriteOnce
      deleteClaim: false
      size: 2Gi

webuser:
  webroles:
  - name: MQWebAdmin
    groups: [devs]
  - name: MQWebAdminRO
    groups: [devs]
  - name: MQWebUser
    groups: [devs]

  apiroles:
  - name: MQWebAdmin
    groups: [devs]
  - name: MQWebAdminRO
    groups: [devs]
  - name: MQWebUser
    groups: ["devs"]

  ldapregistry:
    connect:
      realm: openldap
      host: openldap.default.svc.cluster.local
      port: 389
      ldaptype: Custom
      binddn: cn=admin,dc=szesto,dc=com
      bindpassword: admin
      basedn: dc=szesto,dc=com
      sslenabled: false

    groupdef:
      objectclass: groupOfNames
      groupnameattr: cn
      groupmembershipattr: member

    userdef:
      objectclass: inetOrgPerson
      usernameattr: uid

  allowedhosts: []

  clientauth:
    keystorepass: ""
    truststorepass: ""
    enabled: false

  variables:
  - name: httpsPort
    value: "9443"
  - name: httpHost
    value: '*'
  - name: mqRestCorsAllowedOrigints
    value: '*'
