FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4
USER 0

RUN microdnf install -y wget tar gzip
RUN wget -q https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev922_linux_x86-64.tar.gz && tar zxvf ./mqadv_dev922_linux_x86-64.tar.gz -C /tmp 
