FROM docker.io/golang:1.16.5 AS mqrunner
USER 0
RUN mkdir /go/src/mqrunner
WORKDIR /go/src/mqrunner
COPY mqrunner .
RUN go install ./cmd

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4
USER 0

RUN microdnf --disableplugin=subscription-manager install shadow-utils bc tar procps-ng gzip findutils pam passwd wget util-linux sudo libselinux-utils
RUN microdnf --disableplugin=subscription-manager install bash ca-certificates file gawk glibc-common grep ncurses-compat-libs sed which openldap-clients openssl
RUN microdnf --disableplugin=subscription-manager install libgcc libstdc++

RUN mkdir /tmp/MQServer-noi
COPY MQServer-noi /tmp/MQServer-noi

COPY mq-install-noi.sh mq-install-noi.sh
COPY copy-mq-runtime.sh copy-mq-runtime.sh

RUN mkdir -p /opt/mqm
RUN ./mq-install-noi.sh /tmp/MQServer-noi /opt/mqm 1001

RUN /opt/mqm/bin/security/amqpamcf

# copy mqrunner from go builder
COPY --from=mqrunner /go/bin/cmd /opt/mqm/bin/mqrunner
RUN chown 1001:root /opt/mqm/bin/mqrunner & chmod u+x,g+x,o+x /opt/mqm/bin/mqrunner

EXPOSE 1414 1957 9443

USER 1001

ENV MQ_OVERRIDE_DATA_PATH=/mnt/mqm/data 
ENV MQ_OVERRIDE_INSTALLATION_NAME=Installation1
ENV MQ_USER_NAME="mqm" 
ENV PATH="${PATH}:/opt/mqm/bin"

#ENTRYPOINT ["/opt/mqm/bin/mqrunner"]
