FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4
USER 0

RUN microdnf install -y shadow-utils bc tar procps-ng gzip findutils pam passwd wget util-linux sudo libselinux-utils
RUN microdnf install -y libgcc libstdc++

RUN mkdir /tmp/MQServer-noi
COPY MQServer-noi /tmp/MQServer-noi

COPY mq-install-noi.sh mq-install-noi.sh
COPY copy-mq-runtime.sh copy-mq-runtime.sh

RUN ./mq-install-noi.sh /tmp/MQServer-noi /opt/mqm 1001

RUN /opt/mqm/bin/security/amqpamcf

EXPOSE 1414 1957 9443

ENV MQ_OVERRIDE_DATA_PATH=/mnt/mqm/data MQ_OVERRIDE_INSTALATION_NAME="Installation1" MQ_USER_NAME="mqm" PATH="${PATH}:/opt/mqm/bin"

USER 1001

ENTRYPOINT ["/bin/bash"]
