{{- if .Values.qmspec.ingress.enable }}
{{- if eq .Values.qmspec.ingress.ingressClass "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: {{ include "mqchart.fullname" . | trunc 54 }}-{{ .Values.qmspec.name | trunc 8 }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
{{- if .Values.qmspec.ingress.webcHostname }}
    - {{ .Values.qmspec.ingress.webcHostname }}
{{- end }}
{{- if .Values.qmspec.ingress.qmgrHostname }}
    - {{ .Values.qmspec.ingress.qmgrHostname }}
{{- end }}
  rules:
{{- if .Values.qmspec.ingress.webcHostname }}
  - host: {{ .Values.qmspec.ingress.webcHostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "mqchart.fullname" . | trunc 54 }}-{{ .Values.qmspec.name | trunc 8 }}
            port:
              number: {{ .Values.qmspec.service.httpswebcPort }}
        path: /
        pathType: Prefix
{{- end }}
{{- if .Values.qmspec.ingress.qmgrHostname }}
  - host: {{ .Values.qmspec.ingress.qmgrHostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "mqchart.fullname" . | trunc 54 }}-{{ .Values.qmspec.name | trunc 8 }}
            port:
              number: {{ .Values.qmspec.service.qmgrPort }}
        path: /
        pathType: Prefix
{{- end }}
{{- end }}
{{- end }}
