apiVersion: v1
kind: ConfigMap
metadata:
  name: mqsc-ini-{{ .Release.Name }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
data:
  mqsc.yaml: |-
    {{- toYaml .Values.mq | nindent 4 }}