kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-qm-sts-claim
  namespace: {{ .Release.Namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  