apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqchart.fullname" . | trunc 54 }}-{{ .Values.qmspec.name | trunc 8 }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qmspec.service.serviceType }}
  ports:
  - port: {{ .Values.qmspec.service.qmgrPort }}
    targetPort: 1414
    protocol: TCP
    name: qmgr
  - port: {{ .Values.qmspec.service.httpwebcPort }}
    targetPort: 9080
    protocol: TCP
    name: httpwebc
  - port: 9443
    targetPort: {{ .Values.qmspec.service.httpswebcPort }}
    protocol: TCP
    name: httpswebc
  selector:
    {{- include "mqchart.selectorLabels" . | nindent 4 }}
