kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.qmgr.name }}
  finalizers: []
  labels:
    app.kubernetes.io/component: messaging
    app.kubernetes.io/name: txmq-mq
    app.kubernetes.io/instance: txmq-mq-{{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  serviceName: qmgr
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: messaging
      app.kubernetes.io/name: txmq-mq
      app.kubernetes.io/instance: txmq-mq-{{ .Release.Name }}
      app.kubernetes.io/managed-by: helm
      app.kubernetes.io/created-by: controller-manager
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      finalizers: []
      labels:
        app.kubernetes.io/component: messaging
        app.kubernetes.io/name: txmq-mq
        app.kubernetes.io/instance: txmq-mq-{{ .Release.Name }}
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/created-by: controller-manager
        app.kubernetes.io/version:  {{ .Chart.AppVersion }}
      annotations:
        productVersion: {{ .Values.mqver }}
        productName: IBM MQ Advanced
        productMetric: VIRTUAL_PROCESSOR_CORE
    spec:
      serviceAccount: {{.Release.Name}}-{{.Values.serviceAccount.name}}
      serviceAccountName: {{.Release.Name}}-{{.Values.serviceAccount.name}}
      restartPolicy: Always
      schedulerName: default-scheduler
      # param: affinity
      affinity: {}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      containers:
        - name: mq-mq-qmgr
          image: {{ .Values.image | squote }}
#          terminationMessagePolicy: File
#          terminationMessagePath: /run/termination-log
#          {{- if .Values.resources }}
#          resources:
#            limits:
#              cpu: {{ default "1" .Values.resources.limits.cpu }}
#              memory: {{ default "1Gi" .Values.resources.limits.memory }}
#            requests:
#              cpu: {{ default "1" .Values.resources.requests.cpu }}
#              memory: {{ default "1Gi" .Values.resources.requests.memory }}
#          {{- end }}
          readinessProbe:
            httpGet:
              path: /ready
              port: 40000
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthy
              port: 40000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          env:
            - name: MQ_QMGR_NAME
              value: {{ .Values.qmgr.name | quote }}
            - name: MQ_ENABLE_TLS
              value: "1"
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: 1001
            runAsGroup: 1001
          ports:
            - containerPort: 1414
              protocol: TCP
            - containerPort: 9157
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy }}
          volumeMounts:
            - mountPath: /mnt/mqm/data
              name: mqmdata
            - mountPath: /etc/mqm/mqsc
              name: mqsc-ini
            - mountPath: /etc/mqm/pki/cert
              name: qm-tls
#            - name: oidc-certificate
#              mountPath: /etc/mqm/pki/trust/default
#            - name: zen-ca-certificate
#              mountPath: /etc/mqm/pki/trust/zenca
      volumes:
        - name: mqmdata
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-qm-sts-claim
        - name: mqsc-ini
          configMap:
            name: mqsc-ini-{{ .Release.Name }}
        - name: qm-tls
          secret:
            secretName: qm-tls
#        - name: oidc-certificate
#          secret:
#            secretName: ibmcloud-cluster-ca-cert
#            items:
#              - key: ca.crt
#                path: OIDC_CERTIFICATE.crt
#            defaultMode: 420
#        - name: zen-ca-certificate
#          secret:
#            secretName: internal-nginx-svc-tls
#            items:
#              - key: tls.crt
#                path: ZEN_CERTIFICATE.crt
#            defaultMode: 420

