apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqchart.fullname" . }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 1414
      targetPort: 1414
      protocol: TCP
      name: qmgr
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: httpwebc
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: httpswebc
  selector:
    {{- include "mqchart.selectorLabels" . | nindent 4 }}
