apiVersion: v1
kind: ConfigMap
metadata:
  name: qmini-{{ .Release.Name }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
data:
  qmini.ini: |+
    {{- if .Values.qmini }}
    {{- .Values.mqini | nindent 4 }}
    {{- end }}