apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-{{.Values.qmspec.serviceAccount.name}}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-allow-anyuid-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-anyuid-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mqchart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-allow-anyuid-scc
subjects:
- kind: ServiceAccount
  name: {{.Release.Name}}-{{.Values.qmspec.serviceAccount.name}}
  namespace: {{ .Release.Namespace }}
