apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: openldap
  name: openldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - command:
        - /opt/bitnami/scripts/openldap/entrypoint.sh
        args:
        - /opt/bitnami/scripts/openldap/run.sh
        env:
        - name: LDAP_ROOT
          value: "dc=mqldap,dc=com"
        - name: LDAP_ADMIN_USERNAME
          value: "admin"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
#        - name: BITNAMI_DEBUG
#          value: "true"
        - name: LDAP_ALLOW_ANON_BINDING
          value: "no"
        image: docker.io/bitnami/openldap:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - exit 0
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: openldap
        ports:
        - containerPort: 1636
          protocol: TCP
          name: ssl-ldap
        - containerPort: 1389
          protocol: TCP
          name: tcp-ldap
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - exit 0
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi

        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 1001
          runAsGroup: 0
          capabilities:
            drop:
            - NET_RAW

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ldifs
          name: bootstrap-ldif
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
#      securityContext:
#        seccompProfile:
#          type: RuntimeDefault
      serviceAccount: bitnami-openldap
      serviceAccountName: bitnami-openldap
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bitnami-ldif
        name: bootstrap-ldif
