kind: Service
apiVersion: v1
metadata:
  name: openldap
spec:
  ports:
    - protocol: TCP
      port: 389
      targetPort: tcp-ldap
  selector:
    app: openldap
  type: ClusterIP
  sessionAffinity: None
