apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: openldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
    spec:
      containers:
      - args:
        - /opt/bitnami/scripts/openldap/run.sh
        command:
        - /opt/bitnami/scripts/openldap/entrypoint.sh
        env:
        - name: LDAP_ROOT
          value: dc=mqldap,dc=com
        - name: LDAP_ADMIN_USERNAME
          value: admin
        - name: LDAP_ADMIN_PASSWORD
          value: admin
        image: docker.io/bitnami/openldap:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - exit 0
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: openldap
        ports:
        - containerPort: 1636
          name: ssl-ldap
          protocol: TCP
        - containerPort: 1389
          name: tcp-ldap
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - exit 0
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ldifs
          name: bootstrap-ldif
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: bitnami-openldap
      serviceAccountName: bitnami-openldap
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: bitnami-ldif
        name: bootstrap-ldif
