apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mq-noi-tar
  namespace: mqmq
spec:
  source:
    git:
      uri: 'https://github.com/szesto/mq-operator.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-tar
  output:
    to:
      kind: DockerImage
      name: "image-registry.openshift-image-registry.svc:5000/mqmq/mq-noi-tar:0.1"
