image: image-registry.openshift-image-registry.svc:5000/mqmq/mq-server-rpm:0.1
imagePoolPolicy: Always
mqver: 9.2.2.0

serviceAccount:
  create: true
  name: sa3

qmgr:
  name: qm1
  access:
    defaultuser: 'nobody'
    blockip: [10.5.*]
    blockuser: [karson]
  authority:
  - group: [devs]
    grant: [connect, crt]
    revoke: [dlt]
  - principal: [roky, karson, tobsky]
    grant: [connect, crt]
    revoke: [dlt]
  setauthrec:
  alter:
  - alter qmgr chlauth(enabled)

auth:
  ldap:
    connect:
      ldapHost: openldap.mqmq.svc.cluster.local
      ldapPort: 389
      bindDn: cn=admin,dc=szesto,dc=com
      bindPasswordSecret: admin
      tls: true
    groups:
      groupSearchBaseDn: ou=groups,dc=szesto,dc=com
      objectClass: groupOfNames
      groupNameAttr: cn
      groupMembershipAttr: member
    users:
      userSearchBaseDn: ou=users,dc=szesto,dc=com
      objectClass: inetOrgPerson
      userNameAttr: uid
      shortUserNameAttr: cn

svrconn:
- name: app.channel
  access:
    defaultuser: 'nobody'
    blockip: [192.168.1.*,192.168.10.*]
    blockuser: [roky, karrson, tobsky]
  authority:
  capacity:
    maxclients: 100
    maxmsglen: 4096
    msgpersecond: 100
  tls:
    enable: true
    clientauth: true
    ciphers: strong
  setauthrec:
  alter:

localqueue:
- name: q.a
  descr: local queue a
  put: true
  get: true
  priority: true
  defaultpri: 9
  defaultpersistence: true
  trigger: false
  initq: q.z
  maxdepth: 5000
  maxmsglen: 4194303
  authority:
  - group: [devs]
    grant: [put]
    revoke: [get]
  - group: [sres]
    grant: [get]
    revoke: [browse]
  - principal: [roky, karson]
    grant: [browse]
    revoke: [put, get]
  setauthrec:
  alter:
  - DEFREADA(YES) HARDENBO
