image: image-registry.openshift-image-registry.svc:5000/mqmq/mq-server-rpm:0.1
imagePoolPolicy: Always
mqver: 9.2.2.0

serviceAccount:
  create: true
  name: sa3

qmgr:
  name: qm20

mq:
  qmgr:
    name: qm20
  access:
    blockip: [192.168.*]
    blockuser: [roky, karson, tobsky, kathy]
    allowip: [10.*]
  authority:
    - group: [devs]
      grant: [connect, inq]
    - group: [admins]
      # todo: 'set' on qm on admin only
      grant: [alladm, chg, clr, crt, dlt, dsp]
  alter: []

  auth:
    ldap:
      connect:
        ldaphost: "openldap.mqmq.svc.cluster.local"
        ldapport: 389
        binddn: "cn=admin,dc=szesto,dc=com"
        bindpasswordsecret: "admin"
        tls: false
      groups:
        groupsearchbasedn: "ou=groups,dc=szesto.dc=com"
        objectclass: "groupOfNames"
        groupnameattr: "cn"
        groupmembershipattr: "member"
      users:
        usersearchbasedn: "ou=users,dc=szesto,dc=com"
        objectclass: "inetOrgPerson"
        usernameattr: "uid"
        shortusernameattr: "cn"

  svrconn:
  - svrconnproperties:
      name: app.channel
      maxmsgl: 4096
    tls:
      enabled: false
      clientauth: false
      ciphers: []
    access:
      defaultuser: ""
      blockip: ["10.2.100.*"]
      blockuser: []
      allowip: []
    authority:
      # todo: set mcauser on the channel def
      - group: [devs]
        grant: [chg, clr, crt, dlt, dsp, ctrl, ctrlx]
      - group: [admins]
        # crt is system-wide authority
        grant: [alladm, chg, clr, dlt, dsp]
    alter:
    - monchl(off)
    - alter channel(app.channel) monchl(low)

  localqueue:
  - name: q.a
    defaultprioprity: 2
    defaultpersistence: true
    maxmsgl: 4096
    maxdepth: 1000
    authority:
      - group: [devs]
        grant: [put, get, setall, passall]
      - group: [admins]
        grant: [alladm, chg, clr, dlt, dsp]
  - name: q.b
    like: q.a
