apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qmclaim1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-nfs-storage